## NUMPY ARRAY BASICS##

In [9]:
import numpy as np
import time

 ## CREATING ARRAYS FROM NUMPY#$
 

In [10]:
arr_1d = np.array([1,2,3,4,5,6])
arr_2d = np.array([[1,2,3],[4,5,6]])
print("1D array: ",arr_1d)
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5 6]
2D array:  [[1 2 3]
 [4 5 6]]


## list V/S  numpy arrays

In [11]:
list1 = [1,2,3]
print("list multiplication:", list1 *2)

arry = np.array([1,2,3])
print("array multiplication:", arry *2)

list multiplication: [1, 2, 3, 1, 2, 3]
array multiplication: [2 4 6]


##CECKING THE EFFICIENCY OF THE LISTS AND ARRAYS##

In [12]:
start = time.time()
l1= [i*2 for i in range(10000)]
print("\n operation time    :", time.time()-start)


start = time.time()
a1=np.arange(10000)*2
print("\n operation time    :", time.time()-start)


 operation time    : 0.0006525516510009766

 operation time    : 0.0008032321929931641


##TYPES OF OTHER ARRAYS##

In [13]:
#Zeros Matrix
zeros=np.zeros((3, 4))
print("\nArray of zeros: \n",zeros)

ones =np.ones((4,4))
print("\nArray of ones: \n",ones)

full= np.full((4,4), 7) 
print("\nArray of fulls: \n",full)

random = np.random.random((3,3))
print("\nArray of randoms: \n",random)

sequence = np.arange(0,100,5)
print("\nArray of sequences: \n",sequence)


Array of zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array of fulls: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Array of randoms: 
 [[0.95969118 0.49577205 0.47159536]
 [0.84852033 0.08215246 0.63263477]
 [0.76782069 0.35336544 0.11282488]]

Array of sequences: 
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


## Vector, Matrix, Tensor ##

In [14]:
vector= np.array([1,2,3])
print("vector: ", vector)

matrix = np.array([[1,2,3],[1,2,3]])
print("matrix:\n ", matrix)

tensor = np.array([[[1,2],[2,3]],
                    [[4,5],[6,7]],
                   [[8,9],[9,10]]])
print("Tensor:\n ", tensor)

vector:  [1 2 3]
matrix:
  [[1 2 3]
 [1 2 3]]
Tensor:
  [[[ 1  2]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [ 9 10]]]


## properties of the array##

In [15]:
x1= np.array([[1,2,3],[4,5,6]] )
print("Shape of an array: ", x1.shape)
print("Dimensions: ",x1.ndim)
print("size: ",x1.size)
print("DTYPE: ",x1.dtype)


Shape of an array:  (2, 3)
Dimensions:  2
size:  6
DTYPE:  int64


## Array Reshaping

In [18]:
arr = np.arange(12)
print("Array: ",arr)

reshaping = arr.reshape((3,4))
print("Reshaped: \n", reshaping)

flattened = reshaping.flatten()
print("Flatenned Array: \n",flattened)

#ravel shows you view, instead of copy
ravled = reshaping.ravel()
print("Raveled: \n", ravled)

transpose = reshaping.transpose()
print("Transpose:\n ",transpose)

Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatenned Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
