## ARRAY OPERATIONS

In [2]:
import numpy as np

In [12]:
arr =np.array([1,2,3,4,5,6,7,8,9,10])
print("1D arrray is: ",arr)
print("\nBasic slicing:")
print(arr[0:])
print(arr[:9:2])
print(arr[4:8])
print(arr[: : -1])

1D arrray is:  [ 1  2  3  4  5  6  7  8  9 10]

Basic slicing:
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[5 6 7 8]
[10  9  8  7  6  5  4  3  2  1]


Indexing and slicing with 2D-Array

In [17]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("2D-Array: \n",arr_2d)
print("Specific Element: ", arr_2d[1,2])
print("Specific row: ", arr_2d[1])
print("Specific coulmn: ", arr_2d[:,2])

2D-Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element:  6
Specific row:  [4 5 6]
Specific coulmn:  [3 6 9]


Sorting

In [29]:
unsorted = np.array([7,564,4,7,8,3,2,25,7,8,5,4,356,])
print("unsorted Array: ",unsorted)
print("sorted array:", np.sort(unsorted))

unsorted_2D = np.array([[3,1,2],
                        [9,6,15],
                        [7,8,1]])
print("unsorted 2D array: \n",unsorted_2D)
print("sorted 2D array(axis=1 : row wise (by defualt)): \n", np.sort(unsorted_2D, axis=1))
print("sorted 2D array:(axis=0 : coulmn wise) \n", np.sort(unsorted_2D, axis=0))


unsorted Array:  [  7 564   4   7   8   3   2  25   7   8   5   4 356]
sorted array: [  2   3   4   4   5   7   7   7   8   8  25 356 564]
unsorted 2D array: 
 [[ 3  1  2]
 [ 9  6 15]
 [ 7  8  1]]
sorted 2D array(axis=1 : row wise (by defualt)): 
 [[ 1  2  3]
 [ 6  9 15]
 [ 1  7  8]]
sorted 2D array:(axis=0 : coulmn wise) 
 [[ 3  1  1]
 [ 7  6  2]
 [ 9  8 15]]


## Filtering  of an ARRAY

In [33]:
numbers = np.array([0,1,2,3,4,5,6,7,8,9])
print("Array: ",numbers)

even = numbers[numbers%2==0]
odd = numbers[numbers%2!=0]
print("Even numbers from array is: ", even)
print("odd numbers from array is: ", odd)

Array:  [0 1 2 3 4 5 6 7 8 9]
Even numbers from array is:  [0 2 4 6 8]
odd numbers from array is:  [1 3 5 7 9]


Filter with mask|

In [38]:
mask = numbers>5
print("numbers greater than 5: ",numbers[mask])

# print("numbers greater than 5: ",numbers[numbers>5])

numbers greater than 5:  [6 7 8 9]


## Fancy Techniques

indexing and where clause(np.where())

In [41]:
indices = [0,2,4]
print("indices in numbers:",numbers[indices])

where_result = np.where(numbers>5)
print("np WHERE:", numbers[where_result])

indices in numbers: [0 2 4]
np WHERE: [6 7 8 9]


In [ ]:
condition_array = np.where(numbers>5, numbers*2, numbers)
print("condition array",condition_array)


condition_array = np.where(numbers>5, "True", "False!")

'''ie is like:
if(numbers>5): 
    print("Ture")
else:
    print("False!")'''

print(condition_array)

condition array [ 0  1  2  3  4  5 12 14 16 18]
['False!' 'False!' 'False!' 'False!' 'False!' 'False!' 'True' 'True'
 'True' 'True']
